### ISSUE TITLE
Error in PublicEncrypt Method

### ISSUE THREAD

**Issue by amaennel** [seishun/node-steam-crypto#1]
Im receiving this error. The library is in use by the node-steam library and the error seems to appear while the bot is connecting to steam.

The error:
/home/ubuntu/Desktop/Untitled Folder/node_modules/steam-crypto/index.js:6
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
                                 ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/home/ubuntu/Desktop/Untitled Folder/node_modules/steam-crypto/index.js:6:34)
    at SteamClient.handlers.(anonymous function) (/home/ubuntu/Desktop/Untitled Folder/node_modules/steam/lib/steam_client.js:216:44)
    at SteamClient._netMsgReceived (/home/ubuntu/Desktop/Untitled Folder/node_modules/steam/lib/steam_client.js:157:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/home/ubuntu/Desktop/Untitled Folder/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

I have already done some research and updated my node versions.

I tried both v0.12.8 and v5.1.0.
None of them are working.

Thank you for your help.

**Comment by seishun** [comment]
What's the output of `node --version`?

**Comment by amaennel** [comment]
Interesting... I just changed the version a few minutes ago for another error which was fixed after updating. node -v gave back 5.1.0. But now it gives me 0.10.25 back for some resason.

**Comment by seishun** [comment]
Well, there's your problem.
